apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-26T02:06:44Z"
  name: es-config
  namespace: default
data:
  ES_JAVA_OPTS: -Xms512m -Xmx512m
  elasticsearch.yml: |-
    cluster.name: microk8s-elastic-cluster
    cluster.initial_master_nodes: esnode-0
    discovery.seed_hosts: es-transport
    network.host: "0.0.0.0"
    bootstrap.memory_lock: false
    xpack.security.enabled: false 
