apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-26T02:06:51Z"
  labels:
    app: elasticsearch
  name: es-http
  namespace: default
  resourceVersion: "24350"
  selfLink: /api/v1/namespaces/default/services/es-http
  uid: 9a546e7a-bd18-4eff-a670-dfbaa24486e4
spec:
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: elasticsearch
  sessionAffinity: None
  type: NodePort
