apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-26T02:06:51Z"
  labels:
    app: elasticsearch
  name: es-http
  namespace: default
spec:
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: elasticsearch
  sessionAffinity: None
  type: NodePort
